---
server:
  port: 8085

spring:
  datasource:
    url: jdbc:h2:mem:HRP;INIT=RUNSCRIPT FROM 'classpath:dbscript.sql';
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      path: h2console
      enaled: true